export const BUTTONS = [
  {
    name: "H1",
    text: "Header 1",
    content: "",
    tags: "h1",
    style: "",
    alignment: "",
    capitalization: "",
  },
  {
    name: "H2",
    text: "Header 2",
    content: "",
    tags: "h2",
    style: "",
    alignment: "",
    capitalization: "",
  },
  {
    name: "H3",
    text: "Header 3",
    content: "",
    tags: "h3",
    style: "",
    alignment: "",
    capitalization: "",
  },
  {
    name: "H4",
    text: "Header 4",
    content: "",
    tags: "h4",
    style: "",
    alignment: "",
    capitalization: "",
  },
  {
    name: "H5",
    text: "Header 5",
    content: "",
    tags: "h5",
    style: "",
    alignment: "",
    capitalization: "",
  },
  {
    name: "P",
    text: "Paragraph",
    content: "",
    tags: "p",
    style: "",
    alignment: "",
    capitalization: "",
  },
];
